#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=9

banner "nickneely.dev cutover"

# ── 1 · Preflight ─────────────────────────────────────────────────────────
stage "Preflight: the new site is ready to point at"
say "Order matters here (issue #8): the terminal résumé moves FIRST, so the"
say "risky apex flip becomes a boring one."
step "Confirm the new site deploys clean on its *.vercel.app domain."
note "If you haven't: push feat/front-door's merge to main and let Vercel build."
if command -v pnpm >/dev/null 2>&1 && [[ -f package.json ]]; then
  if confirm "Run 'pnpm validate' locally right now as a sanity check?"; then
    pnpm validate
  fi
fi
ask VERCEL_PREVIEW_ORIGIN "Paste the working *.vercel.app origin (https://...):"
pause "Loaded it in a browser and the NICK hero renders? Press Enter."

# ── 2 · Terminal résumé to its subdomain ──────────────────────────────────
stage "Move the terminal résumé to terminal.nickneely.dev"
say "The legacy interactive résumé keeps living, just not at the front door."
open_url "https://vercel.com/dashboard"
step "Open the OLD résumé project → Settings → Domains."
step "Add domain: terminal.nickneely.dev. Vercel shows the DNS record it wants."
open_url "https://dash.cloudflare.com"
step "In Cloudflare DNS for nickneely.dev, add that record (usually a CNAME"
step "for 'terminal'). Set it to DNS only (grey cloud), not proxied."
pause "Added? Give DNS a minute, then press Enter to check."
if command -v curl >/dev/null 2>&1; then
  if curl -sfI --max-time 15 "https://terminal.nickneely.dev" >/dev/null 2>&1; then
    say "✓ terminal.nickneely.dev answers over HTTPS."
  else
    warn "terminal.nickneely.dev is not answering yet. DNS + certificates can"
    warn "take a few minutes; re-run this wizard later if it still fails."
    confirm "Continue anyway?" || exit 1
  fi
fi

# ── 3 · Apex to the new project ───────────────────────────────────────────
stage "Point nickneely.dev at the new site"
warn "This is the visible flip. The old site stops being nickneely.dev now."
confirm "Ready to move the apex?" || exit 1
step "In the OLD project's Settings → Domains: remove nickneely.dev and www"
step "if they are attached there."
step "In the NEW project's Settings → Domains: add nickneely.dev, then add"
step "www.nickneely.dev and choose 'Redirect to nickneely.dev' (308)."
step "Vercel shows the exact DNS records it wants for each. Add them in"
step "Cloudflare, DNS only (grey cloud), replacing the old apex records."
warn "Touch ONLY the A/CNAME records for @ and www. Leave every MX and TXT"
warn "record alone - Cloudflare Email Routing lives there."
pause "Records saved? Press Enter to verify."
if command -v curl >/dev/null 2>&1; then
  if curl -sf --max-time 20 "https://nickneely.dev" 2>/dev/null | grep -q "NICK"; then
    say "✓ https://nickneely.dev serves the new site."
  else
    warn "Apex not serving the new site yet (propagation can take minutes)."
    confirm "Continue anyway?" || exit 1
  fi
  redirect_target=$(curl -sI --max-time 20 "https://www.nickneely.dev" 2>/dev/null | tr -d '\r' | awk 'tolower($1)=="location:"{print $2}' | tail -n1)
  if [[ "$redirect_target" == "https://nickneely.dev"* ]]; then
    say "✓ www redirects to the apex."
  else
    warn "www is not redirecting to the apex yet (saw: ${redirect_target:-nothing})."
  fi
fi

# ── 4 · Verify the apex in Resend ─────────────────────────────────────────
stage "Verify nickneely.dev for sending in Resend"
say "Per ADR-0003 the apex is the sending domain: mail goes out as"
say "hello@nickneely.dev, and Resend's records live on send. and _domainkey."
open_url "https://resend.com/domains"
step "Add domain: nickneely.dev (region of your choice)."
step "Resend lists DNS records: an MX + TXT (SPF) on send.nickneely.dev and"
step "DKIM records under *._domainkey.nickneely.dev."
step "Add exactly those in Cloudflare, DNS only."
warn "DO NOT touch the apex MX records or the apex 'v=spf1"
warn "include:_spf.mx.cloudflare.net ~all' TXT. contact@nickneely.dev"
warn "forwarding dies if you do."
step "Back in Resend, click Verify and wait for all records to go green."
pause "Domain shows Verified? Press Enter."
if command -v dig >/dev/null 2>&1; then
  apex_mx=$(dig +short MX nickneely.dev | sort | head -n3 | tr '\n' ' ')
  if printf '%s' "$apex_mx" | grep -qi "mx.cloudflare.net"; then
    say "✓ Apex MX still points at Cloudflare Email Routing: $apex_mx"
  else
    warn "Apex MX looks wrong for Cloudflare Email Routing: ${apex_mx:-none}"
    warn "Check this before sending anything - inbound mail may be broken."
  fi
fi

# ── 5 · No tracking in Resend ─────────────────────────────────────────────
stage "Disable open and click tracking"
say "The site runs no third-party surveillance, so its mail doesn't either"
say "(ADR-0003): no links. subdomain, no pixel, no rewritten URLs."
open_url "https://resend.com/settings"
step "Find the tracking settings (Settings, or the domain's configuration)"
step "and turn OFF both open tracking and click tracking."
pause "Both off? Press Enter."

# ── 6 · Vercel Web Analytics ──────────────────────────────────────────────
stage "Enable Vercel Web Analytics"
say "The <Analytics /> component already ships in the app; it just needs the"
say "project toggle."
open_url "https://vercel.com/dashboard"
step "New project → Analytics tab → Enable Web Analytics."
note "Custom events (intro-call-click, newsletter-subscribe) appear once real"
note "traffic sends them."
pause "Enabled? Press Enter."

# ── 7 · Production secrets ────────────────────────────────────────────────
stage "Production environment variables"
say "Four server-side values. They are written to your local .env and you"
say "paste the same four into Vercel → Settings → Environment Variables"
say "(Production). None may ever reach a client bundle - they don't, by"
say "construction, but they also never belong in git."
open_url "https://resend.com/api-keys"
step "Create an API key (sending access is enough)."
ask_secret RESEND_API_KEY "Paste RESEND_API_KEY:"
open_url "https://resend.com/audiences"
step "Open (or create) the newsletter audience and copy its Audience ID."
ask RESEND_AUDIENCE_ID "Paste RESEND_AUDIENCE_ID:"
if [[ -z "$(_existing NEWSLETTER_SIGNING_SECRET || true)" ]]; then
  NEWSLETTER_SIGNING_SECRET=$(node -e "console.log(require('node:crypto').randomBytes(32).toString('hex'))")
  say "Generated a fresh NEWSLETTER_SIGNING_SECRET."
  note "Rotating it later invalidates confirm links in flight - deliberate act."
else
  NEWSLETTER_SIGNING_SECRET=$(_existing NEWSLETTER_SIGNING_SECRET)
  say "Keeping the NEWSLETTER_SIGNING_SECRET already in .env."
fi
open_url "https://github.com/settings/tokens"
step "Create a token that authenticates as nick-neely with repo read access."
warn "Private pushes only show up if the token is YOUR user's token - and the"
warn "site only ever renders 'a private repo', never a name."
ask_secret GITHUB_ACTIVITY_TOKEN "Paste GITHUB_ACTIVITY_TOKEN:"
write_env RESEND_API_KEY "$RESEND_API_KEY"
write_env RESEND_AUDIENCE_ID "$RESEND_AUDIENCE_ID"
write_env NEWSLETTER_SIGNING_SECRET "$NEWSLETTER_SIGNING_SECRET"
write_env GITHUB_ACTIVITY_TOKEN "$GITHUB_ACTIVITY_TOKEN"
open_url "https://vercel.com/dashboard"
step "Now paste all four into the NEW project → Settings → Environment"
step "Variables → Production, then redeploy so they take effect."
pause "All four set in Vercel and redeployed? Press Enter."

# ── 8 · Verify the web surface ────────────────────────────────────────────
stage "Verify the launched site"
say "Checking the production origin end to end."
if command -v curl >/dev/null 2>&1; then
  for path in "/" "/work" "/projects" "/writing" "/subscribe" "/rss.xml" "/sitemap.xml" "/robots.txt"; do
    if curl -sfI --max-time 20 "https://nickneely.dev${path}" >/dev/null 2>&1; then
      say "✓ ${path}"
    else
      warn "✗ ${path} did not answer 200"
    fi
  done
fi
step "Spot-check in a browser: both themes, the door opens, a Post renders"
step "with its OG card visible in a link-preview debugger."
note "Deeper check: run 'pnpm seo:verify' against a fresh local build - it"
note "asserts metadata, JSON-LD, sitemap, robots, and the feed."
pause "Looks right? Press Enter."

# ── 9 · Verify mail, both directions ──────────────────────────────────────
stage "Verify mail: inbound forwarding and outbound alignment"
step "Inbound: send any email to contact@nickneely.dev from another account"
step "and confirm it still arrives where Cloudflare routes it."
step "Outbound: in Resend, send a test email (or use the newsletter confirm"
step "flow on /subscribe with your own address)."
step "Open the received message's original headers (Gmail: 'Show original')."
say "All three must pass, aligned to nickneely.dev:"
say "  SPF: pass · DKIM: pass with d=nickneely.dev · DMARC: pass"
note "DMARC stays at p=none for launch; tightening to p=quarantine after two"
note "clean weeks is issue #12."
pause "Both directions verified? Press Enter."

finish
say "Launch complete. Deferred follow-ups: DMARC p=quarantine (#12), orphaned"
say "Mailgun records cleanup (#13)."
